# Jekyll Defaults
title: Data, Beer, and Stats
description: Some thoughts about some of the best things in life, ... data, beer and stats
baseurl: "" # the subpath of your site, e.g. /blog

url: "http://localhost:4000"
github: http://github.com/rjsteckel

#markdown: redcarpet
markdown: kramdown
highlighter: rouge
permalink: /post/:title/
paginate: 3
gems: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: feed.xml
tags_path: tag.html
navigation:
- text: About
  url: /about/
- text: Archives
  url: /archives/
- text: Tags
  url: /tags/
